- name: Get PGSQL version
  command: psql --version
  changed_when: no
  check_mode: no
  register: pgsql_version_check
  tags:
    - always

- name: Set PGSQL version
  set_fact:
    pgsql_version: "{{ pgsql_version_check['stdout'] | pgsql_version_string }}"
  tags:
    - always
