---
yum_repo_keys:
  - 'RPM-GPG-KEY-ansible-release'

tower_bundle_file: tower_bundle_el7.j2

# List of AWS RHUI (RH Update Infrastructure) repositories to enable
redhat_aws_rhui_repos:
    - rhui-REGION-rhel-server-extras

# List of non-AWS RHUI (RH Update Infrastructure) repositories to enable
redhat_rhui_repos:
    - rhui-rhel-7-server-rhui-extras-rpms

# List of RHSM (RH Subscription Manager) repositories to enable
redhat_rhsm_repos:
    - rhel-7-server-extras-rpms
